/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sblog.view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anthony
 */
public class TelaVenda extends javax.swing.JFrame {

    private TelaVenda eu = null;
    int codigo = 0;
    String nomeArq = "";

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        eu = this;
        //setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnArquivo = new javax.swing.JButton();
        jBLerArquivo = new javax.swing.JButton();
        lNomeAquivo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextCnpj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextValorPedido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextCondicaoPgto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextDataEnvio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaModelo = new javax.swing.JTable();
        jBGravarArquivos = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Arquivo"));
        jPanel1.setToolTipText("");

        jBtnArquivo.setText("Abrir Arquivo");
        jBtnArquivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirArquivoHandler(evt);
            }
        });

        jBLerArquivo.setText("Ler Arquivo");
        jBLerArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLerArquivoActionPerformed(evt);
            }
        });

        lNomeAquivo.setText("arquivo [nome do arquivo] selecionado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lNomeAquivo))
                    .addComponent(jBLerArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNomeAquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLerArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Pedido"));

        jLabel1.setText("CNPJ");

        jLabel2.setText("Empresa");

        jLabel3.setText("Nº Pedido");

        jLabel4.setText("Valor do Pedido");

        jLabel5.setText("Condição de Pagto");

        jLabel6.setText("Data Envio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextEmpresa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(200, 200, 200))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextCondicaoPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 57, Short.MAX_VALUE))
                            .addComponent(jTextDataEnvio))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jTextEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextDataEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextPedido)
                    .addComponent(jTextCondicaoPgto)
                    .addComponent(jTextValorPedido))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        tabelaModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Item", "Descrição", "Quantidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaModelo);
        if (tabelaModelo.getColumnModel().getColumnCount() > 0) {
            tabelaModelo.getColumnModel().getColumn(0).setResizable(false);
            tabelaModelo.getColumnModel().getColumn(1).setResizable(false);
            tabelaModelo.getColumnModel().getColumn(2).setResizable(false);
            tabelaModelo.getColumnModel().getColumn(3).setResizable(false);
        }

        jBGravarArquivos.setText("Gravar Arquivo");
        jBGravarArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarArquivosActionPerformed(evt);
            }
        });

        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBGravarArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBGravarArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jBtnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirArquivoHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirArquivoHandler
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int opcao = chooser.showOpenDialog(eu);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            jBLerArquivo.setEnabled(true);
            nomeArq = chooser.getSelectedFile().getName();
            File currentDirectory = chooser.getCurrentDirectory();
            nomeArq = currentDirectory + File.separator + nomeArq;
            lNomeAquivo.setText(nomeArq);
        } else if (opcao == JFileChooser.CANCEL_OPTION) {
            lNomeAquivo.setText("Opção Candelada");
        }
    }//GEN-LAST:event_AbrirArquivoHandler

    private void jBLerArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLerArquivoActionPerformed
        // TODO add your handling code here:
        if (!nomeArq.equals("")) {

            jBLerArquivo.setEnabled(false);

            List<String> arquivoLido = leitorArquivo(nomeArq);
            System.out.println("---Lendo arquivo-----\n" + arquivoLido);
            carregarTextoTela(arquivoLido);

        } else {
            JOptionPane.showMessageDialog(null, "Arquivo não selecionado", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBLerArquivoActionPerformed

    public void carregarTextoTela(List<String> arquivoLido) {
        String linha = arquivoLido.get(0).trim();

        String cnpjExtraido = linha.substring(linha.indexOf(";") + 1, linha.lastIndexOf(";"));
        jTextCnpj.setText(cnpjExtraido);

        String empresa = linha.substring(linha.lastIndexOf(";") + 1, linha.length());
        jTextEmpresa.setText(empresa);
        //
        String linha2 = arquivoLido.get(1).replace(";", " ");

        String pedidoNum = linha2.substring(2, linha2.indexOf(" ", 2));
        jTextPedido.setText(pedidoNum);

        String valor = linha2.substring(pedidoNum.length() + 3, linha2.indexOf("A"));
        jTextValorPedido.setText(valor);

        String condicao = linha2.substring((valor.length() + pedidoNum.length()) + 2, linha2.length() - 11).trim();
        jTextCondicaoPgto.setText(condicao);

        String data = linha2.substring(linha2.lastIndexOf(" "), linha2.length() - 1).trim();
        jTextDataEnvio.setText(data);

        limparTabela();
        DefaultTableModel tabela = (DefaultTableModel) tabelaModelo.getModel();
        for (int i = 2; i < arquivoLido.size(); i++) {
            String linha3 = arquivoLido.get(i).replace(";", " ");
            String codigoItem = linha3.substring(2, 7);
            String descricao = linha3.substring(codigoItem.length() + 2, codigoItem.length() + 13).trim();
            int tamanho = linha3.lastIndexOf(" ");
            String qtde = linha3.substring((codigoItem.length() + 1) + (descricao.length() + 2), tamanho).trim();
            String subtotal = linha3.substring(linha3.length() - 6, linha3.length()).trim();

            tabela.addRow(new Object[]{codigoItem, descricao, qtde, subtotal});
        }
    }

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jBGravarArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarArquivosActionPerformed
        // TODO add your handling code here:
        gravarArquivo();
        limparCamposTextos();
        limparTabela();
        lNomeAquivo.setText("");
    }//GEN-LAST:event_jBGravarArquivosActionPerformed

    public void limparTabela() {
        int linha = tabelaModelo.getRowCount();
        DefaultTableModel tabela = (DefaultTableModel) tabelaModelo.getModel();
        for (int i = linha - 1; i >= 0; i--) {
            tabela.removeRow(i);
        }
    }

    public void limparCamposTextos() {
        jTextCnpj.setText("");
        jTextEmpresa.setText("");
        jTextPedido.setText("");
        jTextValorPedido.setText("");
        jTextCondicaoPgto.setText("");
        jTextDataEnvio.setText("");

        jTextCnpj.requestFocus();
    }

    public List<String> leitorArquivo(String nameFile) {
        FileReader leitorArquivo = null;
        BufferedReader buferizador = null;
        List<String> listandoString = new ArrayList<>();
        try {
            leitorArquivo = new FileReader(nameFile);
            buferizador = new BufferedReader(leitorArquivo);
            String texto = buferizador.readLine();
            while (texto != null) {
                listandoString.add(texto + "\n");
                texto = buferizador.readLine();
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (buferizador != null && leitorArquivo != null) {
                    buferizador.close();
                    leitorArquivo.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return listandoString;
    }

    public void gravarArquivo() {
        FileWriter gravador = null;
        BufferedWriter buferizador = null;
        String texto = pegarTextoTela();
        try {
            gravador = new FileWriter(nomeArq);
            buferizador = new BufferedWriter(gravador);
            buferizador.write(texto);
//            buferizador.newLine();
            buferizador.flush();
            System.out.println("Arquivo salvo: " + texto);
            JOptionPane.showMessageDialog(null, "Dados Alterados!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (buferizador != null && gravador != null) {
                    gravador.close();
                    buferizador.close();
                }
            } catch (IOException ex) {
                System.out.println("Erro ao fechar buffer");
                ex.printStackTrace();
            }
        }
    }

    public String pegarTextoTela() {

        String cnpj = jTextCnpj.getText().trim();
        String empresa = jTextEmpresa.getText().trim();
        String pedido = jTextPedido.getText().trim();
        String valor = jTextValorPedido.getText().trim();
        String condicao = jTextCondicaoPgto.getText().trim();
        String data = jTextDataEnvio.getText().trim();

        String tabela = pegarTextoTabela();

        return "1;" + cnpj + ";" + empresa
                + "\n2;" + pedido.trim() + ";" + valor.trim() + ";" + condicao.trim() + ";" + data.trim()
                + "\n" + tabela;
    }

    public String pegarTextoTabela() {
        int totalLinhas = tabelaModelo.getRowCount();
        DefaultTableModel tabela = (DefaultTableModel) tabelaModelo.getModel();
        String textoLinha = "";
        int contador = 0;

        System.out.println(totalLinhas);
        //textoLinha = "3;" + String.valueOf(tabela.getValueAt(0, 0));
        //System.out.println(textoLinha);

        while (contador < totalLinhas) {
            textoLinha += "3;" + String.valueOf(tabela.getValueAt(contador, 0))
                    + ";" + String.valueOf(tabela.getValueAt(contador, 1))
                    + ";" + String.valueOf(tabela.getValueAt(contador, 2))
                    + ";" + String.valueOf(tabela.getValueAt(contador, 3)) +"\n";
            contador++;
        }
        System.out.println("tabela :" + textoLinha);
        return textoLinha;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGravarArquivos;
    private javax.swing.JButton jBLerArquivo;
    private javax.swing.JButton jBtnArquivo;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCnpj;
    private javax.swing.JTextField jTextCondicaoPgto;
    private javax.swing.JTextField jTextDataEnvio;
    private javax.swing.JTextField jTextEmpresa;
    private javax.swing.JTextField jTextPedido;
    private javax.swing.JTextField jTextValorPedido;
    private javax.swing.JLabel lNomeAquivo;
    private javax.swing.JTable tabelaModelo;
    // End of variables declaration//GEN-END:variables
}
